-- SecureCloudStorage schema for Supabase PostgreSQL

create table if not exists public.user (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(120) not null unique,
    password_hash varchar(255) not null
);

create index if not exists ix_user_email on public.user (email);

create table if not exists public.stored_files (
    id integer generated by default as identity primary key,
    user_id integer not null references public.user(id),
    original_filename varchar(255) not null,
    encrypted_filename varchar(255) not null unique,
    file_size integer not null,
    uploaded_at timestamptz not null default now()
);

create index if not exists ix_stored_files_user_id on public.stored_files (user_id);
